# Generated by Django 3.2 on 2021-04-30 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20210427_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='bedrooms',
            field=models.IntegerField(default=32),
            preserve_default=False,
        ),
    ]
