# Generated by Django 3.2 on 2021-05-01 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_alter_listing_tutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='school',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='listing',
            name='slug',
            field=models.CharField(max_length=200),
        ),
    ]
