# Generated by Django 3.2.3 on 2021-07-26 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210726_2051'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posting',
            new_name='Tutor_Posting',
        ),
    ]
