# Generated by Django 3.2 on 2021-05-21 04:07

from datetime import datetime
import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_username_useraccount_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='profile_image',
            field=models.ImageField(blank=True, default=accounts.models.get_default_image, max_length=255, null=True, upload_to=accounts.models.get_profile_image_filepath),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='last_login',
            field=models.DateTimeField(auto_now=True, default=datetime.now(), verbose_name='last login'),
            preserve_default=False,
        ),
    ]
