# Generated by Django 3.2.3 on 2021-05-27 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_account_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='hide_email',
            field=models.BooleanField(default=True),
        ),
    ]
