# Generated by Django 3.2 on 2021-04-27 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='school',
            field=models.CharField(default='sdfsdf', max_length=50),
            preserve_default=False,
        ),
    ]
