# Generated by Django 3.2 on 2021-05-01 20:04

from django.db import migrations, models
import tutor.models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0002_tutor_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='photo',
        ),
        migrations.AddField(
            model_name='tutor',
            name='filename',
            field=models.ImageField(blank=True, null=True, upload_to=tutor.models.upload_path),
        ),
    ]
