# Generated by Django 3.2.3 on 2021-08-13 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_task',
            name='end_time',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='daily_task',
            name='start_time',
            field=models.TimeField(blank=True),
        ),
    ]
