# Generated by Django 3.2.3 on 2021-08-06 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='which_day',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
