# Generated by Django 3.2.3 on 2021-08-21 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Schedules', '0002_auto_20210812_1933'),
        ('Schedules', '0002_day_which_day'),
    ]

    operations = [
    ]
