# Generated by Django 3.2.3 on 2021-08-06 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Schedules', '0002_day_which_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='day',
        ),
    ]
