# Generated by Django 3.2.3 on 2021-08-07 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedules', '0003_remove_day_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='tasks',
            field=models.ManyToManyField(related_name='tasks', to='Schedules.daily_task'),
        ),
    ]
