# Generated by Django 3.2.3 on 2021-08-07 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedules', '0004_alter_day_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_task',
            name='end_time',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='daily_task',
            name='start_time',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='day',
            name='tasks',
            field=models.ManyToManyField(to='Schedules.daily_task'),
        ),
    ]
